batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202309282326
train_epochs: 1000
train_workers: 20
vocab: ':emj()kgUFtoQP!Bf6ZE3IAqN/vhMKbxpGH-z;1V&C.c0D*5srX''4#"SaLdWi79wOnul+?,yY2TRJ8 '
width: 1408
