batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202309282333
train_epochs: 1000
train_workers: 20
vocab: 9f-Td64*gNlC/qZ,!1zhBI5AnK3eMuQR.tWaEk?SiHLjJOs+7X#;rF 8cvG(:y"Db&)moxPpVU'Y2w0
width: 1408
