batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202309282350
train_epochs: 1000
train_workers: 20
vocab: djK1*)TU&0eYC3oi:6Lz;+4g-n!F9"/qERxau'V5DSyhAH8 OPtsZm,b7?(.w2klQvBf#IWXGMcJprN
width: 1408
