batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202309290008
train_epochs: 1000
train_workers: 20
vocab: 0!,W8H-m?k+Q/eNAlP;vS'LBORz.17Mthu)#i:X2rV5C4w6JcGqb(D jd*K9FfgonEZ"Iys3&UxTaYp
width: 1408
