batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition\202309290001
train_epochs: 1000
train_workers: 20
vocab: oDZ;xf'z4I,CvJMi-+Qkc85Gd3p6wFmELyhT.YXSB?2!tVHnR9q(O)/&"W*AjbalKrN:1U#s gu7e0P
width: 1408
